### ISSUE TITLE
Add build.gradle file?

### ISSUE THREAD

**Issue by knutwannheden** [jbangdev/jbang-catalog#5]
I was able to use `jbang edit` to edit a single file within this project, but AFAICT the command copies the files into a temporary directory, where they are then edited. And since the `.git` folder doesn't appear to be copied, I cannot easily push any changes from within that editor. This is possiblz a shortcoming of `jbang edit` but otherwise I think having a `build.gradle` file in this repo might solve the problem.

**Comment by maxandersen** [comment]
yeah, the fix for this is doing https://github.com/jbangdev/jbang/issues/462
